name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      # Install and configure Git LFS
      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull
      
      # Ensure large files are tracked by Git LFS
      - name: Track large files with Git LFS
        run: |
          git lfs track "model/*.h5"
          git add .gitattributes
          git commit -m "Track large files with Git LFS" || echo "No changes to commit"
      
      # Push to Hugging Face Hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://loko-dev:$HF_TOKEN@huggingface.co/spaces/loko-dev/skin-vision
          git push --force origin main
